#!/usr/bin/env bash

#        _                 _ _ _
#  _ __ (_)_______ __  ___| | (_)_ _  __ _ ___
# | '  \| (_-<_-< '_ \/ -_) | | | ' \/ _` (_-<
# |_|_|_|_/__/__/ .__/\___|_|_|_|_||_\__, /__/
#               |_|                  |___/
# common misspellings of commands

# vim
alias bim=vim
alias nim=vim

# git
alias got=git
alias gir=git

# make
alias male=make

# exit
alias exot=exit

# clear
alias claer=clear

# ls
alias sl=ls

#  _ _ ___ _ _  __ _ _ __  ___
# | '_/ -_) ' \/ _` | '  \/ -_)
# |_| \___|_||_\__,_|_|_|_\___|
#
# reassignment of commands that make more sense

alias yarn=yarnpkg

#               _
#  __ ___ _ __ | |__  ___ ___
# / _/ _ \ '  \| '_ \/ _ (_-<
# \__\___/_|_|_|_.__/\___/__/
#
# novel combinations of already-existing command for added functionality

# asusctl commands
alias pmode='asusctl profile -P Performance'
alias bmode='asusctl profile -P Balanced'
alias qmode='asusctl profile -P Quiet'

# clears screen and lists current dir
alias cls='clear && echo "${PS1@P}""ls" && ls'
alias cla='clear && echo "${PS1@P}""ls" && ls -A'
alias cl=clear

# ls aliases
alias lh='ls -lah'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# tar aliases
alias untar='tar -xvf'

# xz with max compression and resources
alias fxz='xz -9 -T0'

# shorter unxz
alias uxz='unxz'

# unxz-like alias for gz
alias ungz='gzip -d'

# vim hex editor
alias hvim='vim -c "%!xxd" -c "set ft=xxd"'

#  _ __  __ _ __ _ _ ___ ___
# | '  \/ _` / _| '_/ _ (_-<
# |_|_|_\__,_\__|_| \___/__/
#
# additional functions/more complicated intrinsic aliasing 

# tmux attach to session
tat() { tmux attach -t "$1"; }

# convert every non-dotfile in the directory to unix
dirtounix() { if [ -n "$(command -v dos2unix)" ]; then { for f in *; do dos2unix "$f"; done; }; else { return 1; }; fi }

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# alert alias for long running commands
if [ -f /usr/bin/notify-send ]; then
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi

# mkdir and cd
mkcd() { mkdir -p "$@" && cd "$@" || exit; }
